[workspace]
members = ["rust", "rust/engine", "rust/fuzztest_macro"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.100"
clap = { version = "4.6.1", features = ["derive", "env"] }
convert_case = "0.4.0"
googletest = "0.14.3"
humantime = "2.4.0"
inventory = "0.3.20"
num-traits = "0.2"
postcard = { version = "1.0.0", features = ["use-std"] }
proc-macro-crate = "3.4.0"
proc-macro2 = "1.0.106"
quote = "1.0.45"
rand = { version = "0.10.1", features = ["std_rng"] }
serde = { version = "1.0", features = ["derive"] }
spin = "0.10.0"
syn = { version = "2.0.117", features = ["extra-traits", "full", "parsing", "printing", "visit-mut"] }
tempfile = "3.27.0"
