[package]
name = "fuzztest-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.4.0"
proc-macro2 = "1.0.106"
proc-macro-crate = "3.4.0"
quote = "1.0.45"
syn = { version = "2.0.117", features = ["extra-traits", "full", "parsing", "printing", "visit-mut"] }


[dev-dependencies]
googletest = "0.14.3"
