// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef FUZZTEST_FUZZTEST_INTERNAL_DOMAINS_FLAT_MAP_IMPL_H_
#define FUZZTEST_FUZZTEST_INTERNAL_DOMAINS_FLAT_MAP_IMPL_H_

#include <cstddef>
#include <optional>
#include <tuple>
#include <type_traits>

#include "absl/random/bit_gen_ref.h"
#include "absl/random/distributions.h"
#include "absl/status/status.h"
#include "absl/strings/str_format.h"
#include "absl/strings/string_view.h"
#include "absl/types/span.h"
#include "./fuzztest/internal/domains/domain_base.h"
#include "./fuzztest/internal/domains/serialization_helpers.h"
#include "./fuzztest/internal/logging.h"
#include "./fuzztest/internal/meta.h"
#include "./fuzztest/internal/printer.h"
#include "./fuzztest/internal/serialization.h"
#include "./fuzztest/internal/status.h"
#include "./fuzztest/internal/type_support.h"

namespace fuzztest::internal {

// FlatMap takes a domain factory function (flat mapper) and an input domain
// for each parameter of the factory function. The output domain is what the
// flat mapper returns and the domain that FlatMap represents. I.e., the "output
// domain" is re-created dynamically, as it depends on values created by the
// input domains.
template <typename FlatMapper, typename... InputDomain>
using FlatMapOutputDomain = std::decay_t<
    std::invoke_result_t<FlatMapper, value_type_t<InputDomain>...>>;

// Base class for FlatMapImpl and ReversibleFlatMapImpl.
// Meant to be used as:
// ```c++
// template <typename FlatMapper, typename... InputDomain>
// class ConcreteFlatMapImpl
//     : public FlatMapImplBase<ConcreteFlatMapImpl<FlatMapper, InputDomain...>,
//                              FlatMapper, InputDomain...> {
//   ...
// };
// ```
template <typename Derived, typename FlatMapper, typename... InputDomain>
class FlatMapImplBase
    : public domain_implementor::DomainBase<
          Derived,
          // The user value is the user value of the output domain.
          value_type_t<FlatMapOutputDomain<FlatMapper, InputDomain...>>,
          // The corpus value is a tuple where the first element is the output
          // domain itself, the second element is the corpus value of the output
          // domain, and the rest are the corpus values of the input domains.
          std::tuple<
              FlatMapOutputDomain<FlatMapper, InputDomain...>,
              corpus_type_t<FlatMapOutputDomain<FlatMapper, InputDomain...>>,
              corpus_type_t<InputDomain>...>> {
 public:
  using typename FlatMapImplBase::DomainBase::corpus_type;
  using typename FlatMapImplBase::DomainBase::value_type;

  static constexpr size_t kOutputDomainIdx = 0;
  static constexpr size_t kOutputCorpusValIdx = 1;
  static constexpr size_t kInputCorpusValsOffset = 2;

  FlatMapImplBase() = default;
  explicit FlatMapImplBase(FlatMapper flat_mapper, InputDomain... input_domains)
      : flat_mapper_(std::move(flat_mapper)),
        input_domains_(std::move(input_domains)...) {}

  corpus_type Init(absl::BitGenRef prng) {
    if (auto seed = this->MaybeGetRandomSeed(prng)) return *seed;
    auto input_corpus_vals = std::apply(
        [&](auto&... input_domains) {
          // Use `std::make_tuple` instead of CTAD (`std::tuple{...}`) to avoid
          // calling the copy constructor when there is a single input domain
          // whose corpus type is already a `std::tuple`.
          return std::make_tuple(input_domains.Init(prng)...);
        },
        input_domains_);
    auto output_domain = GetOutputDomain(input_corpus_vals);
    auto output_corpus_val = output_domain.Init(prng);
    return std::tuple_cat(
        std::tuple{std::move(output_domain), std::move(output_corpus_val)},
        std::move(input_corpus_vals));
  }

  void Mutate(corpus_type& val, absl::BitGenRef prng,
              const domain_implementor::MutationMetadata& metadata,
              bool only_shrink) {
    // There is no way to tell whether the current output corpus value is
    // consistent with a new output domain generated by mutated inputs, so
    // mutating the inputs forces re-initialization of the output domain. This
    // means that, when shrinking, we cannot mutate the inputs, as
    // re-initializing would lose the "still crashing" output value.
    bool mutate_inputs = !only_shrink && absl::Bernoulli(prng, 0.1);
    if (mutate_inputs) {
      ApplyIndex<kNumInputValues>([&](auto... I) {
        // The first two fields of `val` are the output domain and the output
        // corpus value, so skip them.
        (std::get<I>(input_domains_)
             .Mutate(std::get<I + kInputCorpusValsOffset>(val), prng, metadata,
                     only_shrink),
         ...);
      });
      // Generate a new output domain and output corpus value.
      // We can't write `std::get<...>(val) = ...` because there are domains
      // and corpus types that don't support assignment. So we manually destroy
      // the old objects and construct new ones in place.
      // We must compute both before reconstructing either to ensure `val`
      // is not left in an invalid state if `GetOutputDomain` or `Init` throws.
      auto output_domain = GetOutputDomain(val);
      auto output_corpus_val = output_domain.Init(prng);
      ReconstructInPlace(std::get<kOutputDomainIdx>(val),
                         std::move(output_domain));
      ReconstructInPlace(std::get<kOutputCorpusValIdx>(val),
                         std::move(output_corpus_val));
      return;
    }
    std::get<kOutputDomainIdx>(val).Mutate(std::get<kOutputCorpusValIdx>(val),
                                           prng, metadata, only_shrink);
  }

  value_type GetValue(const corpus_type& v) const {
    return std::get<kOutputDomainIdx>(v).GetValue(
        std::get<kOutputCorpusValIdx>(v));
  }

  auto GetPrinter() const { return Printer{}; }

  std::optional<corpus_type> ParseCorpus(const IRObject& obj) const {
    auto input_corpus_vals =
        ParseWithDomainTuple(input_domains_, obj, /*skip=*/1);
    if (!input_corpus_vals.has_value()) {
      return std::nullopt;
    }
    absl::Status input_values_validity =
        ValidateInputValues(*input_corpus_vals);
    if (!input_values_validity.ok()) {
      absl::FPrintF(GetStderr(), "[!] %s", input_values_validity.message());
      return std::nullopt;
    }
    auto output_domain = GetOutputDomain(*input_corpus_vals);
    // We know obj.Subs()[0] exists because ParseWithDomainTuple succeeded.
    auto output_corpus_val = output_domain.ParseCorpus((*obj.Subs())[0]);
    if (!output_corpus_val.has_value()) {
      return std::nullopt;
    }
    return std::tuple_cat(
        std::tuple{std::move(output_domain), *std::move(output_corpus_val)},
        *std::move(input_corpus_vals));
  }

  IRObject SerializeCorpus(const corpus_type& v) const {
    IRObject obj;
    auto& subs = obj.MutableSubs();

    // 1. Serialize the output corpus value.
    subs.push_back(std::get<kOutputDomainIdx>(v).SerializeCorpus(
        std::get<kOutputCorpusValIdx>(v)));

    // 2. Serialize the input corpus values.
    ApplyIndex<kNumInputValues>([&](auto... I) {
      (subs.push_back(
           std::get<I>(input_domains_)
               .SerializeCorpus(std::get<I + kInputCorpusValsOffset>(v))),
       ...);
    });
    return obj;
  }

  absl::Status ValidateCorpusValue(const corpus_type& corpus_value) const {
    // Check input values first.
    absl::Status input_values_validity = ValidateInputValues(corpus_value);
    if (!input_values_validity.ok()) return input_values_validity;
    // Check the output value.
    return std::get<kOutputDomainIdx>(corpus_value)
        .ValidateCorpusValue(std::get<kOutputCorpusValIdx>(corpus_value));
  }

 protected:
  const std::tuple<InputDomain...>& input_domains() const {
    return input_domains_;
  }
  static constexpr size_t kNumInputValues = sizeof...(InputDomain);

  // Returns the output domain for a `tuple` with or without the output domain
  // and value as the leading elements, and with the input values as the last
  // `kNumInputValues` elements.
  template <typename Tuple>
  FlatMapOutputDomain<FlatMapper, InputDomain...> GetOutputDomain(
      const Tuple& tuple) const {
    static_assert(is_tuple_v<Tuple> &&
                  std::tuple_size_v<Tuple> >= kNumInputValues);
    static constexpr size_t kOffset =
        std::tuple_size_v<Tuple> - kNumInputValues;
    return ApplyIndex<kNumInputValues>([&](auto... I) {
      // The first field of `tuple` may be the output corpus value, so skip it.
      return flat_mapper_(std::get<I>(input_domains_)
                              .GetValue(std::get<kOffset + I>(tuple))...);
    });
  }

  // Validates the input values for a `tuple` with or without the output domain
  // and value as the leading elements, and with the input values as the last
  // `kNumInputValues` elements.
  template <typename Tuple>
  absl::Status ValidateInputValues(const Tuple& tuple) const {
    static_assert(is_tuple_v<Tuple> &&
                  std::tuple_size_v<Tuple> >= kNumInputValues);
    static constexpr size_t kOffset =
        std::tuple_size_v<Tuple> - kNumInputValues;
    return ApplyIndex<kNumInputValues>([&](auto... I) {
      absl::Status input_values_validity = absl::OkStatus();
      (
          [&] {
            if (!input_values_validity.ok()) return;
            const absl::Status s =
                std::get<I>(input_domains_)
                    .ValidateCorpusValue(std::get<kOffset + I>(tuple));
            input_values_validity =
                Prefix(s, absl::StrCat("Invalid value for ", Derived::GetName(),
                                       "()-ed domain"));
          }(),
          ...);
      return input_values_validity;
    });
  }

 private:
  struct Printer {
    void PrintCorpusValue(const corpus_type& corpus_value,
                          domain_implementor::RawSink out,
                          domain_implementor::PrintMode mode) const {
      // There is no useful way to print the input values, so we just print the
      // output value by delegating to the output domain.
      domain_implementor::PrintValue(
          std::get<kOutputDomainIdx>(corpus_value),
          std::get<kOutputCorpusValIdx>(corpus_value), out, mode);
    }
  };

  FlatMapper flat_mapper_;
  std::tuple<InputDomain...> input_domains_;
};

template <typename FlatMapper, typename... InputDomain>
class FlatMapImpl
    : public FlatMapImplBase<FlatMapImpl<FlatMapper, InputDomain...>,
                             FlatMapper, InputDomain...> {
 public:
  using typename FlatMapImpl::FlatMapImplBase::corpus_type;
  using typename FlatMapImpl::FlatMapImplBase::value_type;

  using FlatMapImpl::FlatMapImplBase::FlatMapImplBase;

  static constexpr absl::string_view GetName() { return "FlatMap"; }

  std::optional<corpus_type> FromValue(const value_type&) const {
    // We cannot infer the input corpus from the output value, or even determine
    // from which output domain the output value came.
    return std::nullopt;
  }
};

// -----------------------------------------------------------------------------
// ReversibleFlatMap Implementation
// -----------------------------------------------------------------------------

template <typename FlatMapper, typename InvMapper, typename... InputDomain>
class ReversibleFlatMapImpl
    : public FlatMapImplBase<
          ReversibleFlatMapImpl<FlatMapper, InvMapper, InputDomain...>,
          FlatMapper, InputDomain...> {
 public:
  using typename ReversibleFlatMapImpl::FlatMapImplBase::corpus_type;
  using typename ReversibleFlatMapImpl::FlatMapImplBase::value_type;

  static_assert(
      std::is_invocable_v<InvMapper, const value_type&> &&
          std::is_same_v<
              std::invoke_result_t<InvMapper, const value_type&>,
              std::optional<std::tuple<value_type_t<InputDomain>...>>>,
      "ReversibleFlatMap must have an inverse mapper that takes the output "
      "value and returns an optional of a tuple of the input values.");

  ReversibleFlatMapImpl() = default;
  explicit ReversibleFlatMapImpl(FlatMapper flat_mapper, InvMapper inv_mapper,
                                 InputDomain... input_domains)
      : ReversibleFlatMapImpl::FlatMapImplBase(std::move(flat_mapper),
                                               std::move(input_domains)...),
        inv_mapper_(std::move(inv_mapper)) {}

  static constexpr absl::string_view GetName() { return "ReversibleFlatMap"; }

  std::optional<corpus_type> FromValue(const value_type& v) const {
    // 1. Recover the input values using the user-provided inverse mapper.
    auto input_user_vals = std::invoke(inv_mapper_, v);
    if (!input_user_vals.has_value()) return std::nullopt;

    // 2. Map input user values into input corpus values.
    auto input_corpus_vals =
        ApplyIndex<ReversibleFlatMapImpl::FlatMapImplBase::kNumInputValues>(
            [&](auto... I)
                -> std::optional<std::tuple<corpus_type_t<InputDomain>...>> {
              // Use `std::make_tuple` instead of CTAD (`std::tuple{...}`) to
              // avoid calling the copy constructor when there is a single input
              // domain whose corpus type is already a `std::tuple`.
              auto inner_corpus_vals = std::make_tuple(
                  std::get<I>(this->input_domains())
                      .FromValue(std::get<I>(*input_user_vals))...);
              bool has_nullopt =
                  (!std::get<I>(inner_corpus_vals).has_value() || ...);
              if (has_nullopt) return std::nullopt;
              return std::make_tuple(
                  *std::move(std::get<I>(inner_corpus_vals))...);
            });
    if (!input_corpus_vals.has_value()) return std::nullopt;

    if (!this->ValidateInputValues(*input_corpus_vals).ok())
      return std::nullopt;

    // 3. Re-instantiate the dynamically generated output domain.
    auto output_domain = this->GetOutputDomain(*input_corpus_vals);

    // 4. Map the output user value into the output corpus value.
    auto output_corpus_val = output_domain.FromValue(v);
    if (!output_corpus_val.has_value()) return std::nullopt;

    if (!output_domain.ValidateCorpusValue(*output_corpus_val).ok()) {
      return std::nullopt;
    }

    // 5. Assemble the final corpus tuple.
    return std::tuple_cat(
        std::tuple{std::move(output_domain), *std::move(output_corpus_val)},
        *std::move(input_corpus_vals));
  }

 private:
  InvMapper inv_mapper_;
};

}  // namespace fuzztest::internal

#endif  // FUZZTEST_FUZZTEST_INTERNAL_DOMAINS_FLAT_MAP_IMPL_H_
