[package]
name = "fuzztest"
version = "0.1.0"
edition = "2024"

[[test]]
name = "trybuild"
path = "tests/trybuild.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
coverage = { path = "coverage" }
engine = { path = "engine", package = "engine-ffi" }
fuzztest-macro = { path = "fuzztest_macro" }
humantime.workspace = true
inventory.workspace = true
num-traits.workspace = true
postcard.workspace = true
rand.workspace = true
serde.workspace = true
spin.workspace = true
tempfile.workspace = true

[dev-dependencies]
googletest = "0.14.3"

[dev-dependencies.trybuild]
version = "1.0.103"
features = ["diff"]

[profile.fuzztest]
inherits = 'release'
panic = 'abort'
opt-level = "s"
debug = true
split-debuginfo = "packed"
